#!/bin/bash

ft rojo "Introduzca los siguientes comandos para:\n\n" 

ft Amarillo "\tarbol - Mostrar directorios y ficheros en forma jer\xc3\xa1rquica\n
\tbuscar [NOM_ARCH] [DIR] - Busca el archivo NOM_ARCH en el directorio DIR\n
\tinfosis - Mostrar informaci\xc3\xb3n del sistema\n
\tfecha - Mostrar la fecha del sistema\n
\thora - Mostrar la hora del sistema\n
\tprebeplayer - Ejecutar el reproductor de m\xc3\xbasica\n
\tahorcado - Acceder al juego ahorcado\n
\thannoi - Acceder al juego de las torres de hannoi versiOn torre Eiffel\n
\tft [FORMATO] [CADENA] - Imprimir CADENA con el FORMATO indicado en\n 
\t\t\t\tlos argumentos\n
\tcreditos - Mostrar nombres de autores de 'Prebeshell'\n
\tsalir - Salir de la prebeshell\n";